#!/usr/bin/env php
<?php

/*
 * This file builds index.php
 */

//TODO: If someone has time to clean this code up, please do so.

require_once __DIR__.'/src/Builder/Minifier.php';
require_once __DIR__.'/src/Builder/minify/html.php';
require_once __DIR__.'/src/Builder/minify/js.php';
require_once __DIR__.'/src/Builder/minify/css.php';
require_once __DIR__.'/src/Builder/functions.php';

register_shutdown_function('fatal');


writeln('Building index.php');

if(!from_cli())
{
    build_fail('This file must be run from the cli.');
}


$contents = '<?php';

writeln('Searching for files...');

$files =    new RecursiveIteratorIterator(
                new RecursiveDirectoryIterator(__DIR__.'/src'),
                RecursiveIteratorIterator::SELF_FIRST
            );

writeln('Adding files...');

$builder = explode('/', get_path(__DIR__.'/src/Builder'));

foreach($files as $name => $object){

    $target = explode('/', get_path($name));
    
    if(array_slice($target, 0, count($builder)) == $builder)
    {
        continue;            
    }
        
    if(is_file($name)) {

        $file = file_get_contents($name);

        if(substr($file, 0, 5) == '<?php')
        {
            $file = substr($file, 5);
        }

        $file = preg_replace_callback(
          '#config\\("(.+?)"\\)#s',
          'replace_config',
          $file
        );
        
        $file = preg_replace_callback(
          '#config\\(\'(.+?)\'\\)#s',
          'replace_config',
          $file
        );
        
        $file = preg_replace_callback(
          '#\<import resource="(.+?)" \/\>#s',
          'replace_static',
          $file
        );
        
        $file = preg_replace_callback(
          '#require "(.+?)";#s',
          'replace_require',
          $file
        );
        
        $file = preg_replace_callback(
          '#require \'(.+?)\';#s',
          'replace_require',
          $file
        );
        

        $contents .= $file;
    }
}

$contents .= ' OneClick::dispatch(@$_GET[\'id\']);';

writeln('Writing file...');

file_put_contents(__DIR__.'/index.php', $contents);

writeln('Compressing file...');

$contents = php_strip_whitespace(__DIR__.'/index.php');

file_put_contents(__DIR__.'/index.php', $contents);

writeln('Testing file...');

ob_start();
include __DIR__.'/index.php';
ob_get_clean();

writeln('Successfully built index.php');
